apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --controller statefulset -f kompose.yml.txt
    kompose.version: 1.30.0 (HEAD)
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  creationTimestamp: null
  labels:
    io.kompose.service: gotalk-dbpost
  name: gotalk-dbpost
  namespace: myapps
spec:
  clusterIP: None
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: gotalk-dbpost
  type: ClusterIP
