apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotalk-app
  namespace: myapps
  labels:
    app: gotalk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gotalk
  template:
    metadata:
      labels:
        app: gotalk
    spec:
      containers:
        - name: gotalk
          # 아래 주소는 본인 ghcr 주소로 변경하세요!
          image: ghcr.io/colah16/gotalk:sha-1f1bc5a
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: UMASK
              value: "002"
            - name: TZ
              value: Asia/Seoul
            - name: DB_NAME
              value: "gotalk_v5" 
              # set usercolr (not message color)
            - name: NATS_URL
              value: "nats://gotalk-nats-headless:4222"
            - name: DB_HOST
              value: "gotalk-dbpost"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gotalk-db-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gotalk-db-secret
                  key: password
          resources:
              # cpu: p30 ? m / p95 ? m / max ? m
              # mem: p95 ? Mi / max ? Mi
            limits:
              # 멀티코어 허용해야 함. 코어 
              # cpu, max의 2배 or max +1000 중 큰
              # mem, max의 1.7배 or + 150 중 큰.
              cpu: 1001m 
              memory: "1640Mi"
            requests:
              # 최소 수치/ 20 50
              # cpu, p30의 1배
              # cpu, 단, p30이 p95의 반보다 작으면 p95
              # 좀 느리면 되지
              # mem, p95의 1배
              cpu: 20m
              # 이건 제한이 아니다..
              memory: "50Mi"

